name: Chrome Extension CI

on:
  push:
    branches-ignore:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate Chrome Extension
        run: |
          # Validate manifest.json
          if [ ! -f "lighthouse-chrome-extension/manifest.json" ]; then
            echo "Error: manifest.json not found"
            exit 1
          fi
          
          # Check required files exist
          required_files=(
            "lighthouse-chrome-extension/background.js"
            "lighthouse-chrome-extension/devtools.html"
            "lighthouse-chrome-extension/devtools.js"
            "lighthouse-chrome-extension/panel.html"
            "lighthouse-chrome-extension/panel.js"
            "lighthouse-chrome-extension/panel.css"
            "lighthouse-chrome-extension/audit-script.js"
          )
          
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Error: Required file $file not found"
              exit 1
            fi
          done
          
          echo "✅ Chrome extension structure validated"

      - name: Package Extension
        run: |
          cd lighthouse-chrome-extension
          zip -r ../chrome-extension.zip .
          echo "✅ Extension packaged successfully"